export const shoppingInitialState = {
  products: [
    {
      id: 1,
      img: "https://http2.mlstatic.com/D_NQ_NP_716492-MLA52853049595_122022-O.webp",
      title: "Colchones de aire o espuma",
      text: "Para reducir la presión en las áreas vulnerables.",
      bgcolor: "green",
      ccolor: "white",
      price: 20000,
    },
    {
      id: 2,
      img: "https://www.arcor.com/ar/dist/images/nuestros_negocios/pic_alimentos.jpg",
      title: "Colchones de aire o espuma",
      text: "Para reducir la presión en las áreas vulnerables.",
      bgcolor: "blue",
      ccolor: "yellow",
      price: 20000,
    },
    {
      id: 3,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt7RNCSJqdha63RVEuZP6fPixgYXOdUpq1aQ&s",
      title: "Colchones de aire o espuma",
      text: "Para reducir la presión en las áreas vulnerables.",
      bgcolor: "pink",
      ccolor: "orange",
      price: 20000,
    },
    {
      id: 4,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJjOhFJXx2SBPoPyMMphgYJUIc_Wxbq-QnQA&s",
      title: "Colchones de aire o espuma",
      text: "Para reducir la presión en las áreas vulnerables.",
      bgcolor: "red",
      ccolor: "black",
      price: 20000,
    },
    {
      id: 5,
      img: "https://http2.mlstatic.com/D_NQ_NP_679220-MLA52534604764_112022-O.webp",
      title: "Colchones de aire o espuma",
      text: "Para reducir la presión en las áreas vulnerables.",
      bgcolor: "black",
      ccolor: "white",
      price: 20000,
    },
  ],
  cart: [],
};
